### PR TITLE
chore: migrate to Vitest

### PR DESCRIPTION
**Pull request by Sepush**
Signed-off-by: Sepush <sepush@outlook.com>

jest
jest-treemate

Vitest
vitest-treemate

### CODE REVIEW

**Comment by Sepush** [comment]
should merged after https://github.com/07akioni/treemate/pull/118 to get ci pass

**Comment by 07akioni** [comment]
> should merged after #118 to get ci pass

合并了重新跑 CI 全挂了？

**Comment by Sepush** [comment]
> > should merged after #118 to get ci pass
> 
> 合并了重新跑 CI 全挂了？

vitest 需要node >= 14 这里的 CI 还是 10 12 14 所以会挂，在上一个 PR 我已经改成了 14 16 我想这是GitHub 的缓存

**Comment by 07akioni** [comment]
先合了再说，反正这个库也不怎么动

**Comment by 07akioni** [comment]
看了一下还在挂着，缺少 lcov 文件

**Pull request merged**
